apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  name: phi-4
  namespace: model-deployment
  annotations:
    opendatahub.io/hardware-profile-name: gpu-profile
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/model-type: generative
    openshift.io/display-name: phi-4
    security.opendatahub.io/enable-auth: 'false'
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  baseRefs:
    - name: phi-4
  model:
    name: phi-4
    uri: 'hf://RedHatAI/phi-4'
  replicas: 1
  router:
    gateway:
      refs:
        - name: model-deployment-inference
          namespace: openshift-ingress
    route: {}
  template:
    containers:
      - env:
          - name: VLLM_ADDITIONAL_ARGS
            value: '--tensor_parallel_size=1'
        name: main
        resources:
          limits:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: '1'
          requests:
            cpu: '4'
            memory: 8Gi
            nvidia.com/gpu: '1'
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
